version: "2"

run:
  tests: false

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  default: none
  enable:
    - asciicheck
    - bodyclose
    # - copyloopvar  # requires go >= 1.22, this module is still on go 1.21
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      # Default: 60
      lines: 70
      # Checks the number of statements in a function.
      # If lower than 0, disable the check.
      # Default: 40
      statements: 50
    gocritic:
      enabled-checks:
        - deferInLoop
        - ruleguard
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowed-packages:
                - github.com/anchore/go-make
                - github.com/anchore/go-make/lang
    staticcheck:
      dot-import-whitelist:
        - github.com/anchore/go-make
        - github.com/anchore/go-make/lang

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 25
  uniq-by-line: false

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      # See https://golangci-lint.run/docs/formatters/configuration/#gci
      sections:
        - standard # Standard section: captures all standard packages.
        - default  # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/anchore)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
