name: "Validations"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  Static-Analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: build/go.mod
          cache-dependency-path: build/go.sum

      - run: make static-analysis

  Unit-Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            build/go.sum

      - run: make test
